# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20161217_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc',
            field=models.FileField(upload_to='cars'),
        ),
    ]
