# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-14 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170111_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc',
            field=models.FileField(upload_to='input_files'),
        ),
    ]
